# Generated by Django 5.1.7 on 2025-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('time', models.DateTimeField()),
                ('free', models.BooleanField(default=True)),
            ],
        ),
    ]
